### ISSUE TITLE
Syntax for Applicatives

### ISSUE THREAD

**Issue by jonifreeman** [fantasyland/sweet-fantasies#3]
Should we add syntax to apply Applicatives?

For instance:

```
/*  
  $ap f(x, y, z)

  Desugared: f.ap(x).ap(y).ap(z)

  $ap(f(100)(x, y, z)

  Desugared: f(100).ap(x).ap(y).ap(z)
*/
macro $ap {
  case $f:ident($x:expr (,) ...) => {
    $f $(.ap($x)) ...
  }
  case ($f:expr)($x:expr (,) ...) => {
    $f $(.ap($x)) ...
  }
}
```

Any comments?

**Comment by markandrus** [comment]
I like it : )

**Comment by jonifreeman** [comment]
I let this rest here for awhile. The syntax makes use of applicative idiom nicely readable but the original form is not bad either. So a conservatist in me says that don't add it :)

**Comment by puffnfresh** [comment]
I really like it. :+1:

**Comment by jonifreeman** [comment]
Added https://github.com/pufuwozu/sweet-fantasies/commit/d6f94cffb70c812955c5904ca7a6337479ed1c72
